baseurl: "/"
languageCode: "en-us"
defaultContentLanguage: "en"
# defaultContentLanguage: "zh"
title: "joplin notes"
theme: "hugo-prose"
googleAnalytics: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
paginate: 100
contentDir: content/posts

permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, rss, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: search
      url: "#"
      identifier: menu-search
      weight: 50

params:
  homePosts: 100
  mainSections: ["draft", "post"]
  editLink: 
  authorDelimiter: " / "
  pageFeatures: 
  description: >
  footer: >
  
  # license: >
  #   Text and figures are licensed under [Creative Commons Attribution CC BY
  #   4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
  #   licensed under MIT. The full source is available at
  #   https://github.com/yihui/hugo-prose.

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
